// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class MinorProjectTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), DesiredCapabilities.firefox());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void minorProject() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(1030, 693));
    driver.findElement(By.cssSelector(".fa-user-plus")).click();
    driver.findElement(By.id("exampleInputEmail1")).sendKeys("Surajkumar8987673516@gmail.com");
    driver.findElement(By.id("password")).sendKeys("suraj");
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("name")).sendKeys("Suraj kumarSingh");
    {
      WebElement element = driver.findElement(By.id("exampleInputEmail1"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).clickAndHold().perform();
    }
    {
      WebElement element = driver.findElement(By.id("exampleInputEmail1"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.id("exampleInputEmail1"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).release().perform();
    }
    driver.findElement(By.id("exampleInputEmail1")).click();
    driver.findElement(By.id("exampleInputEmail1")).sendKeys("suraj31kumar1999");
    driver.findElement(By.cssSelector(".col-md-6")).click();
    driver.findElement(By.id("profession")).click();
    driver.findElement(By.id("profession")).sendKeys("student");
    driver.findElement(By.id("phone")).click();
    driver.findElement(By.id("phone")).sendKeys("9876543210");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("123");
    driver.findElement(By.id("cpassword")).click();
    driver.findElement(By.id("cpassword")).sendKeys("123");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    assertThat(driver.switchTo().alert().getText(), is("Register Successfully... Redirecting to Login.."));
    driver.findElement(By.id("email")).sendKeys("Surajkumar8987673516@gmail.com");
    driver.findElement(By.id("password")).sendKeys("suraj");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("suraj31kumar1999@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("123");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    assertThat(driver.switchTo().alert().getText(), is("Password is Wrong"));
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("1234");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    assertThat(driver.switchTo().alert().getText(), is("Password is Wrong"));
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("password")).sendKeys("suraj");
    driver.findElement(By.id("email")).sendKeys("Surajkumar8987673516@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("8988");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    assertThat(driver.switchTo().alert().getText(), is("Password is Wrong"));
    driver.findElement(By.cssSelector("form")).click();
    driver.findElement(By.id("password")).click();
    driver.findElement(By.cssSelector(".btn-primary")).click();
    assertThat(driver.switchTo().alert().getText(), is("Password is Wrong"));
    driver.findElement(By.id("email")).sendKeys("Surajkumar8987673516@gmail.com");
    driver.findElement(By.id("password")).sendKeys("suraj");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("8988");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    assertThat(driver.switchTo().alert().getText(), is("Password is Wrong"));
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("123");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    assertThat(driver.switchTo().alert().getText(), is("Password is Wrong"));
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("suraj31kumar1999@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.cssSelector(".btn-primary")).click();
    assertThat(driver.switchTo().alert().getText(), is("Password is Wrong"));
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("suraj@gmail.com");
    driver.findElement(By.id("password")).click();
    driver.findElement(By.id("password")).sendKeys("8988");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    assertThat(driver.switchTo().alert().getText(), is("User Login Successful..."));
    driver.findElement(By.linkText("Lecture")).click();
    driver.findElement(By.linkText("Class")).click();
    driver.findElement(By.linkText("Wanna JOIN")).click();
    driver.findElement(By.linkText("Class")).click();
    driver.findElement(By.linkText("Wanna Create")).click();
    driver.findElement(By.cssSelector(".form-control")).click();
    driver.findElement(By.cssSelector(".form-control")).sendKeys("1");
    driver.findElement(By.cssSelector(".btn-secondary")).click();
    driver.findElement(By.cssSelector(".VsTVUAD89KWleD0YRVsD")).click();
    driver.findElement(By.id("inputGroup-sizing-default")).click();
    driver.findElement(By.id("inputGroup-sizing-default")).sendKeys("C:\\fakepath\\052615_0721_Howtocreate1.png");
    driver.findElement(By.id("inputGroupFileAddon04")).click();
    driver.findElement(By.linkText("Services")).click();
    driver.findElement(By.linkText("About")).click();
    driver.findElement(By.cssSelector(".ml-3")).click();
    driver.findElement(By.cssSelector(".btn:nth-child(5)")).click();
    driver.findElement(By.linkText("Lecture")).click();
    driver.findElement(By.linkText("Login")).click();
    driver.findElement(By.id("email")).sendKeys("Surajkumar8987673516@gmail.com");
    driver.findElement(By.id("password")).sendKeys("suraj");
    driver.findElement(By.cssSelector(".btn-outline-dark")).click();
    driver.findElement(By.id("exampleInputEmail1")).sendKeys("Surajkumar8987673516@gmail.com");
    driver.findElement(By.id("password")).sendKeys("suraj");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    assertThat(driver.switchTo().alert().getText(), is("Error Found"));
    driver.findElement(By.cssSelector(".ml-5")).click();
  }
}
